{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-19767",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/bugzilla.kernel.org\/show_bug.cgi?id=205609",
                    "name": "https:\/\/bugzilla.kernel.org\/show_bug.cgi?id=205609",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/bugzilla.kernel.org\/show_bug.cgi?id=205707",
                    "name": "https:\/\/bugzilla.kernel.org\/show_bug.cgi?id=205707",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/cdn.kernel.org\/pub\/linux\/kernel\/v5.x\/ChangeLog-5.4.2",
                    "name": "https:\/\/cdn.kernel.org\/pub\/linux\/kernel\/v5.x\/ChangeLog-5.4.2",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/git.kernel.org\/cgit\/linux\/kernel\/git\/torvalds\/linux.git\/commit\/?id=4ea99936a1630f51fc3a2d61a58ec4a1c4b7d55a",
                    "name": "https:\/\/git.kernel.org\/cgit\/linux\/kernel\/git\/torvalds\/linux.git\/commit\/?id=4ea99936a1630f51fc3a2d61a58ec4a1c4b7d55a",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/torvalds\/linux\/commit\/4ea99936a1630f51fc3a2d61a58ec4a1c4b7d55a",
                    "name": "https:\/\/github.com\/torvalds\/linux\/commit\/4ea99936a1630f51fc3a2d61a58ec4a1c4b7d55a",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "The Linux kernel before 5.4.2 mishandles ext4_expand_extra_isize, as demonstrated by use-after-free errors in __ext4_expand_extra_isize and ext4_xattr_set_entry, related to fs\/ext4\/inode.c and fs\/ext4\/super.c, aka CID-4ea99936a163."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2019-12-12T20:15Z",
    "lastModifiedDate": "2019-12-12T23:46Z"
}