{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2019-14864",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-14864",
                    "name": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=CVE-2019-14864",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/ansible\/ansible\/issues\/63522",
                    "name": "https:\/\/github.com\/ansible\/ansible\/issues\/63522",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/ansible\/ansible\/pull\/63527",
                    "name": "https:\/\/github.com\/ansible\/ansible\/pull\/63527",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "Ansible, versions 2.9.x before 2.9.1, 2.8.x before 2.8.7 and Ansible versions 2.7.x before 2.7.15, is not respecting the flag no_log set it to True when Sumologic and Splunk callback plugins are used send tasks results events to collectors. This would discloses and collects any sensitive data."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2020-01-02T15:15Z",
    "lastModifiedDate": "2020-01-02T15:15Z"
}